<a href="https://colab.research.google.com/github/Ira00/nn2022/blob/main/LR_2/LR_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота №2
студентки 3 курсу групи КН-31
Івахненко Ірини

## Завдання 1

Cтворити набір даних із заданим розподілом (розподіл та розмір за власним рішенням), визначити його властивості (shape, rank, size, axis)


In [3]:
import tensorflow as tf
import random
matrix = tf.constant([[[3, 4],
                        [1, 10]],
                       [[6, 7],
                        [10, 22]],
                       [[23, 6],
                        [18, 31]]])

changeable_tensor = tf.Variable([[10., 3],
                      [5, 12]])

randomN = tf.random.Generator.from_seed(22)

randomN = randomN.normal(shape=(3, 2))
print(randomN, '\n')
randomN = randomN * random.randint(2, 5)
print(matrix, '\n')
print(randomN, '\n')
print('Shape: ',matrix.shape, '\n')
print('Rank: ',matrix.ndim, '\n')
print('Size: ', tf.size(matrix).numpy(), '\n')
print('Last axis : ',matrix.shape[-1], '\n')



tf.Tensor(
[[-0.7531523   2.0261486 ]
 [-0.06997604  0.85445154]
 [ 0.1175475   0.03493892]], shape=(3, 2), dtype=float32) 

tf.Tensor(
[[[ 3  4]
  [ 1 10]]

 [[ 6  7]
  [10 22]]

 [[23  6]
  [18 31]]], shape=(3, 2, 2), dtype=int32) 

tf.Tensor(
[[-3.0126092   8.104594  ]
 [-0.27990416  3.4178061 ]
 [ 0.47019     0.13975568]], shape=(3, 2), dtype=float32) 

Shape:  (3, 2, 2) 

Rank:  3 

Size:  12 

Last axis :  2 



## Завдання 2

Продемонструвати основні математичні операції над тензорами.

In [4]:
print(matrix)
print('\n Addition: \n', matrix + 10)
print('\n Multiplication: \n', matrix * 10)
print('\n Multiplication_2: \n', tf.multiply(matrix, 10))
print('\n Subtraction: \n', matrix - 10)
print('\n Matrix mutliplication: \n', matrix @ matrix)
print('\n Matrix mutliplication_2: \n', tf.matmul(matrix, matrix))

print('Min: ',tf.reduce_min(matrix))
print('Max: ',tf.reduce_max(matrix))
print('Sum: ',tf.reduce_sum(matrix))


tf.Tensor(
[[[ 3  4]
  [ 1 10]]

 [[ 6  7]
  [10 22]]

 [[23  6]
  [18 31]]], shape=(3, 2, 2), dtype=int32)

 Addition: 
 tf.Tensor(
[[[13 14]
  [11 20]]

 [[16 17]
  [20 32]]

 [[33 16]
  [28 41]]], shape=(3, 2, 2), dtype=int32)

 Multiplication: 
 tf.Tensor(
[[[ 30  40]
  [ 10 100]]

 [[ 60  70]
  [100 220]]

 [[230  60]
  [180 310]]], shape=(3, 2, 2), dtype=int32)

 Multiplication_2: 
 tf.Tensor(
[[[ 30  40]
  [ 10 100]]

 [[ 60  70]
  [100 220]]

 [[230  60]
  [180 310]]], shape=(3, 2, 2), dtype=int32)

 Subtraction: 
 tf.Tensor(
[[[-7 -6]
  [-9  0]]

 [[-4 -3]
  [ 0 12]]

 [[13 -4]
  [ 8 21]]], shape=(3, 2, 2), dtype=int32)

 Matrix mutliplication: 
 tf.Tensor(
[[[  13   52]
  [  13  104]]

 [[ 106  196]
  [ 280  554]]

 [[ 637  324]
  [ 972 1069]]], shape=(3, 2, 2), dtype=int32)

 Matrix mutliplication_2: 
 tf.Tensor(
[[[  13   52]
  [  13  104]]

 [[ 106  196]
  [ 280  554]]

 [[ 637  324]
  [ 972 1069]]], shape=(3, 2, 2), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tens

## Завдання 3

Reshape, інтеграцію з np.array

In [17]:
import numpy as np
print(tf.reshape(matrix, [3,4]))
print('\n', np.array(matrix))
print(type(matrix))
print(type(np.array(matrix)))

tf.Tensor(
[[ 3  4  1 10]
 [ 6  7 10 22]
 [23  6 18 31]], shape=(3, 4), dtype=int32)

 [[[ 3  4]
  [ 1 10]]

 [[ 6  7]
  [10 22]]

 [[23  6]
  [18 31]]]
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'numpy.ndarray'>
